cluster-generic-submit-cmd: "jobsubmit"
cluster-generic-status-cmd: "jobstatus"
cluster-generic-cancel-cmd: "qdel"
executor: cluster-generic
jobscript: "jobscript.sh"
jobs: 3840
scheduler: greedy
rerun-incomplete: true
max-jobs-per-second: 50
max-status-checks-per-second: 50
latency-wait: 300
local-cores: 64
